### ISSUE TITLE
User can generate an SQL script.

### ISSUE THREAD

**Issue by thebearingedge** [thebearingedge/pg-bump#1]
# ✅ Tasks  
- [x] Test-drive a function for copying a new empty script by name.
- [x] Test-drive execution of CLI.
- [x] Define a `yargs` command for executing `create` function.
- [x] Enable option to override default destination. 

```bash
~/project-directory λ pg-bump create foo.sql
[pg-bump] Creating migration file...
created: migrations/1494462120852_foo.sql
```
